# Generated by Django 3.2.3 on 2021-07-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('patient_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Not specified', 'Not specified')], max_length=13)),
                ('patient_history', models.TextField(blank=True, null=True)),
                ('patient_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity_assessment_method', models.CharField(blank=True, choices=[('', ''), ('Self assessed', 'Self assessed'), ('Genetic data', 'Genetic data')], max_length=13, null=True)),
                ('initial_diagnosis', models.TextField(blank=True, null=True)),
                ('age_at_initial_diagnosis', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_id', models.CharField(max_length=250, unique=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('collection_event', models.CharField(blank=True, max_length=250, null=True)),
                ('months_since_collection_one', models.PositiveIntegerField(blank=True, null=True)),
                ('age_in_years_at_collection', models.PositiveIntegerField()),
                ('diagnosis', models.TextField()),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('tumor_type', models.CharField(max_length=100)),
                ('primary_site', models.CharField(max_length=250)),
                ('collection_site', models.CharField(max_length=250)),
                ('stage', models.CharField(blank=True, max_length=30, null=True)),
                ('staging_system', models.CharField(blank=True, max_length=250, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('grading_system', models.CharField(blank=True, max_length=250, null=True)),
                ('virology_status', models.TextField(blank=True, null=True)),
                ('share_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('treatment_naive_at_collection', models.CharField(blank=True, max_length=100, null=True)),
                ('treated', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not specified', 'Not specified')], max_length=13, null=True)),
                ('prior_treatment', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not specified', 'Not specified')], max_length=13, null=True)),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('host_strain', models.CharField(max_length=250)),
                ('host_strain_full', models.TextField()),
                ('engraftment_site', models.CharField(max_length=250)),
                ('engraftment_type', models.CharField(max_length=250)),
                ('sample_type', models.CharField(max_length=250)),
                ('sample_state', models.CharField(blank=True, max_length=250, null=True)),
                ('passage_number', models.CharField(max_length=250)),
                ('publications', models.TextField()),
                ('validation_technique', models.TextField()),
                ('validation_description', models.TextField()),
                ('passages_validated', models.CharField(max_length=250)),
                ('validation_host_strain_full', models.TextField()),
                ('provider_type', models.CharField(max_length=250)),
                ('model_accessibility', models.CharField(max_length=250)),
                ('europdx_access_modality', models.CharField(choices=[('Transnational access', 'Transnational access'), ('Collaboration only', 'Collaboration only')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=250)),
                ('provider_name', models.CharField(max_length=250)),
                ('provider_abbreviation', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=250)),
            ],
        ),
    ]
