# Generated by Django 3.2.3 on 2021-07-26 06:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdx',
            fields=[
                ('patient_id', models.CharField(max_length=200)),
                ('patient_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('not specified', 'Not specified')], max_length=13)),
                ('patient_history', models.TextField(blank=True, null=True)),
                ('patient_ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity_assessment_method', models.CharField(blank=True, choices=[('self assessed', 'Self assessed'), ('genetic data', 'Genetic data')], max_length=13, null=True)),
                ('initial_diagnosis', models.TextField(blank=True, null=True)),
                ('age_at_initial_diagnosis', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_id', models.CharField(max_length=250, unique=True)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('collection_event', models.CharField(blank=True, max_length=250, null=True)),
                ('months_since_collection_one', models.PositiveIntegerField(blank=True, null=True)),
                ('age_in_years_at_collection', models.PositiveIntegerField()),
                ('diagnosis', models.TextField()),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('tumor_type', models.CharField(max_length=100)),
                ('primary_site', models.CharField(max_length=250)),
                ('collection_site', models.CharField(max_length=250)),
                ('stage', models.CharField(blank=True, max_length=30, null=True)),
                ('staging_system', models.CharField(blank=True, max_length=250, null=True)),
                ('grade', models.CharField(blank=True, max_length=30, null=True)),
                ('grading_system', models.CharField(blank=True, max_length=250, null=True)),
                ('virology_status', models.TextField(blank=True, null=True)),
                ('treatment_info_shareable', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3)),
                ('treatment_naive_at_collection', models.CharField(choices=[('naive', 'Treatment naive'), ('not naive', 'Not treatment naive'), ('not specified', 'Not specified')], max_length=13)),
                ('treated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('unknown', 'Unknown')], max_length=13)),
                ('prior_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('unknown', 'Unknown')], max_length=13)),
                ('model_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('host_strain', models.CharField(max_length=250)),
                ('host_strain_full', models.TextField()),
                ('engraftment_site', models.CharField(max_length=250)),
                ('engraftment_type', models.CharField(max_length=250)),
                ('sample_type', models.CharField(max_length=250)),
                ('sample_state', models.CharField(blank=True, max_length=250, null=True)),
                ('passage_number', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('publications', models.TextField(blank=True, null=True)),
                ('validation_techniques', models.TextField()),
                ('validation_description', models.TextField()),
                ('passages_validated', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('validation_host_strain_full', models.TextField()),
                ('provider_type', models.CharField(max_length=250)),
                ('model_accessibility', models.CharField(max_length=250)),
                ('europdx_access_modality', models.CharField(choices=[('transnational', 'Transnational access'), ('collaboration', 'Collaboration only')], max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=50)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_abbreviation', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
